### ISSUE TITLE
Episodio 8 - Se salta

### ISSUE THREAD

**Issue by dpshelio** [carpentries-i18n/python-novice-gapminder-es#5]
Algo mal en la cabezera

**Comment by dpshelio** [comment]
Ahora no se salta pero "objetives" debería de decir "objectives".

**Comment by dpshelio** [comment]
Arreglado ya en transifex.

**Comment by orchid00** [comment]
hay q cerrar el issue @dpshelio ?

**Comment by dpshelio** [comment]
El 8 ya no se salta :man_dancing:
