### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by orchid00** [carpentries-i18n/python-novice-gapminder-es#7]
- [x] el link del título va a https://carpentries-i18n.github.io/python-novice-gapminder/index/ pero deberia ir a https://carpentries-i18n.github.io/python-novice-gapminder/index.html (no se por que no lleva es en el URL) links to theme carpentries-i18n/carpentry-theme#12

**Comment by dpshelio** [comment]
Resuelto! :tada:
